- name: Install package
  ansible.builtin.apt:
    name: dhcpcd5
    state: present
    update_cache: true

- name: Configure static IP address
  ansible.builtin.blockinfile:
    dest: /etc/dhcpcd.conf
    block: "{{ dhcpcd_static_ip_configuration }}"
  notify: Restart dhcpcd service

- name: Start and enable service
  ansible.builtin.systemd:
    name: dhcpcd
    state: started
    enabled: true
    daemon_reload: true
