- name: Converge
  hosts: all
  vars:
    dhcpcd_static_ip_configuration: |
      interface eth0
      static ip_address={{ ansible_default_ipv4.address }}/16
      static routers={{ ansible_default_ipv4.gateway }}
      static domain_name_servers={{ ansible_dns.nameservers[0] }}
  roles:
    - role: ansible-raspberry-dhcpcd
      tags: dhcpcd
